 eureka:
     client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
 server:
     port: 8999

 spring:
     application:
       name: config-client1
     cloud:
       config:
#          name: config-server-dev
          label: master
          profile: dev
#         uri: http://localhost:8888/
          discovery:
            enable: true
            serviceId: config-server

